USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'DATN_WebBHDT')
BEGIN
    CREATE DATABASE DATN_WebBHDT;
END
GO


-- TẠO LOGIN Ở CẤP SERVER
IF NOT EXISTS (SELECT * FROM sys.sql_logins WHERE name = 'DEV_BACKEND')
BEGIN
    CREATE LOGIN DEV_BACKEND 
    WITH PASSWORD = 'DEV', 
         CHECK_POLICY = OFF, 
         CHECK_EXPIRATION = OFF;
END
GO

USE DATN_WebBHDT;
GO

-- TẠO USER TRONG DATABASE + GÁN LOGIN
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'DEV_BACKEND')
BEGIN
    CREATE USER DEV_BACKEND FOR LOGIN DEV_BACKEND;
END
GO

-- CẤP QUYỀN
EXEC sp_addrolemember 'db_owner', 'DEV_BACKEND';
GO



/*===== TABLES =====*/

-- TAI_KHOAN
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TAI_KHOAN' AND xtype='U')
CREATE TABLE TAI_KHOAN(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	tendangnhap NVARCHAR(255) NOT NULL UNIQUE,
	matkhau NVARCHAR(255) NOT NULL,
	vaitro BIT DEFAULT 0 NOT NULL,
	hoveten NVARCHAR(255) NOT NULL,
	sodienthoai VARCHAR(15) NOT NULL UNIQUE,
	email NVARCHAR(255) NOT NULL UNIQUE,
	trangthai BIT DEFAULT 0 NOT NULL,
	ngaytao DATETIME NOT NULL
);
GO

-- DIA_CHI
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='DIA_CHI' AND xtype='U')
CREATE TABLE DIA_CHI(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	taikhoan INT NOT NULL,
	diachi NVARCHAR(255) NOT NULL
);
GO

-- SAN_PHAM
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='SAN_PHAM' AND xtype='U')
CREATE TABLE SAN_PHAM(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	tensanpham NVARCHAR(255) NOT NULL,
	dongia BIGINT DEFAULT 0 CHECK (dongia >= 0) NOT NULL,
	loai INT NOT NULL,
	thuonghieu INT NOT NULL,
	anhgoc NVARCHAR(255) NOT NULL
);
GO

-- SP_LOAI
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='SP_LOAI' AND xtype='U')
CREATE TABLE SP_LOAI(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	loai NVARCHAR(255) NOT NULL
);
GO

-- SP_THUONG_HIEU
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='SP_THUONG_HIEU' AND xtype='U')
CREATE TABLE SP_THUONG_HIEU(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	thuonghieu NVARCHAR(255) NOT NULL
);
GO

-- SP_THONG_SO
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='SP_THONG_SO' AND xtype='U')
CREATE TABLE SP_THONG_SO(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	sanpham INT NOT NULL,
	thongso NVARCHAR(255) NOT NULL,
	mausac NVARCHAR(255) NOT NULL,
	soluong INT DEFAULT 0 CHECK (soluong >= 0) NOT NULL
);
GO

-- ANH_SP
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ANH_SP' AND xtype='U')
CREATE TABLE ANH_SP(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	sanpham INT NOT NULL,
	diachianh NVARCHAR(255) NOT NULL
);
GO

-- HOA_DON
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='HOA_DON' AND xtype='U')
CREATE TABLE HOA_DON(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	taikhoan INT NOT NULL,
	ngaytao DATETIME NOT NULL,
	giahoadon BIGINT DEFAULT 0 CHECK (giahoadon >= 0) NOT NULL,
	trangthai NVARCHAR(255) NOT NULL,
	noidung NVARCHAR(255) NOT NULL
);
GO

-- HD_CHI_TIET
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='HD_CHI_TIET' AND xtype='U')
CREATE TABLE HD_CHI_TIET(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	hoadon INT NOT NULL,
	sanpham INT NOT NULL,
	dongia BIGINT DEFAULT 0 CHECK (dongia >= 0) NOT NULL,
	soluong INT DEFAULT 0 CHECK (soluong >= 0) NOT NULL
);
GO

-- THANH_TOAN
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='THANH_TOAN' AND xtype='U')
CREATE TABLE THANH_TOAN(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	hoadon INT NOT NULL,
	phuongthuc NVARCHAR(255) NOT NULL,
	sotien BIGINT DEFAULT 0 CHECK (sotien >= 0) NOT NULL,
	ngaythanhtoan DATETIME NOT NULL,
	magiaodich NVARCHAR(255) NOT NULL,
	taikhoan INT NOT NULL,
	ngaytao DATETIME NOT NULL,
	ngaycapnhat DATETIME NOT NULL
);
GO

-- GIO_HANG
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='GIO_HANG' AND xtype='U')
CREATE TABLE GIO_HANG(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	sanpham INT NOT NULL,
	taikhoan INT NOT NULL
);
GO

-- GOP_Y
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='GOP_Y' AND xtype='U')
CREATE TABLE GOP_Y(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	taikhoan INT NOT NULL,
	noidung NVARCHAR(255) NOT NULL,
	ngaytao DATETIME NOT NULL
);
GO

-- DANH_GIA
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='DANH_GIA' AND xtype='U')
CREATE TABLE DANH_GIA(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	taikhoan INT NOT NULL,
	sanpham INT NOT NULL,
	noidung NVARCHAR(255) NOT NULL,
	diemso INT DEFAULT 0 CHECK (diemso >= 0 AND diemso <= 5) NOT NULL
);
GO

-- YEU_THICH
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='YEU_THICH' AND xtype='U')
CREATE TABLE YEU_THICH(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	sanpham INT NOT NULL,
	taikhoan INT NOT NULL
);
GO


/*===== FOREIGN KEY =====*/

-- fk_TAIKHOAN_DIACHI
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_TAIKHOAN_DIACHI'
)
ALTER TABLE DIA_CHI
ADD CONSTRAINT fk_TAIKHOAN_DIACHI
FOREIGN KEY (taikhoan) REFERENCES TAI_KHOAN(id);
GO

-- fk_TAIKHOAN_HOADON
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_TAIKHOAN_HOADON'
)
ALTER TABLE HOA_DON
ADD CONSTRAINT fk_TAIKHOAN_HOADON
FOREIGN KEY (taikhoan) REFERENCES TAI_KHOAN(id);
GO

-- fk_TAIKHOAN_GIOHANG
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_TAIKHOAN_GIOHANG'
)
ALTER TABLE GIO_HANG
ADD CONSTRAINT fk_TAIKHOAN_GIOHANG
FOREIGN KEY (taikhoan) REFERENCES TAI_KHOAN(id);
GO

-- fk_TAIKHOAN_GOPY
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_TAIKHOAN_GOPY'
)
ALTER TABLE GOP_Y
ADD CONSTRAINT fk_TAIKHOAN_GOPY
FOREIGN KEY (taikhoan) REFERENCES TAI_KHOAN(id);
GO

-- fk_TAIKHOAN_DANHGIA
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_TAIKHOAN_DANHGIA'
)
ALTER TABLE DANH_GIA
ADD CONSTRAINT fk_TAIKHOAN_DANHGIA
FOREIGN KEY (taikhoan) REFERENCES TAI_KHOAN(id);
GO

-- fk_TAIKHOAN_YEU_THICH
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_TAIKHOAN_YEU_THICH'
)
ALTER TABLE YEU_THICH
ADD CONSTRAINT fk_TAIKHOAN_YEU_THICH
FOREIGN KEY (taikhoan) REFERENCES TAI_KHOAN(id);
GO

-- fk_SANPHAM_LOAI
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_SANPHAM_LOAI'
)
ALTER TABLE SAN_PHAM
ADD CONSTRAINT fk_SANPHAM_LOAI
FOREIGN KEY (loai) REFERENCES SP_LOAI(id);
GO

-- fk_SANPHAM_THUONGHIEU
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_SANPHAM_THUONGHIEU'
)
ALTER TABLE SAN_PHAM
ADD CONSTRAINT fk_SANPHAM_THUONGHIEU
FOREIGN KEY (thuonghieu) REFERENCES SP_THUONG_HIEU(id);
GO

-- fk_SANPHAM_THONGSO
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_SANPHAM_THONGSO'
)
ALTER TABLE SP_THONG_SO
ADD CONSTRAINT fk_SANPHAM_THONGSO
FOREIGN KEY (sanpham) REFERENCES SAN_PHAM(id);
GO

-- fk_SANPHAM_ANH
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_SANPHAM_ANH'
)
ALTER TABLE ANH_SP
ADD CONSTRAINT fk_SANPHAM_ANH
FOREIGN KEY (sanpham) REFERENCES SAN_PHAM(id);
GO

-- fk_SANPHAM_HOADONCT
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_SANPHAM_HOADONCT'
)
ALTER TABLE HD_CHI_TIET
ADD CONSTRAINT fk_SANPHAM_HOADONCT
FOREIGN KEY (sanpham) REFERENCES SAN_PHAM(id);
GO

-- fk_SANPHAM_GIOHANG
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_SANPHAM_GIOHANG'
)
ALTER TABLE GIO_HANG
ADD CONSTRAINT fk_SANPHAM_GIOHANG
FOREIGN KEY (sanpham) REFERENCES SAN_PHAM(id);
GO

-- fk_SANPHAM_YEUTHICH
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_SANPHAM_YEUTHICH'
)
ALTER TABLE YEU_THICH
ADD CONSTRAINT fk_SANPHAM_YEUTHICH
FOREIGN KEY (sanpham) REFERENCES SAN_PHAM(id);
GO

-- fk_HOADON_HDCHITIET
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_HOADON_HDCHITIET'
)
ALTER TABLE HD_CHI_TIET
ADD CONSTRAINT fk_HOADON_HDCHITIET
FOREIGN KEY (hoadon) REFERENCES HOA_DON(id);
GO

-- fk_THANHTOAN_HOADON
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_THANHTOAN_HOADON'
)
ALTER TABLE THANH_TOAN
ADD CONSTRAINT fk_THANHTOAN_HOADON
FOREIGN KEY (hoadon) REFERENCES HOA_DON(id);
GO

-- fk_THANHTOAN_TAIKHOAN
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys WHERE name = 'fk_THANHTOAN_TAIKHOAN'
)
ALTER TABLE THANH_TOAN
ADD CONSTRAINT fk_THANHTOAN_TAIKHOAN
FOREIGN KEY (taikhoan) REFERENCES TAI_KHOAN(id);
GO
